name: Remote Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Удаляем старый контейнер, если он есть
            sudo docker rm -f my-web-auto || true
            # Запускаем новый
            sudo docker run -d --name my-web-auto -p 8083:80 nginx
            
